name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Test build-and-scan-image action
        uses: ./
        with:
          path: ./testdata
          tag: testdata:${{ github.sha }}
          snyk-enable: true
          snyk-token: ${{ secrets.SNYK_TOKEN }}
